### ISSUE TITLE
Freeze Star icon shows as Nuclear Stomper icon during miracle crafting description

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#100]
Wrong icon displayed during crafting description. The snippets of text scripts and screenshots will do the explaining.

StageSelect.tsc
```
#1020
<KEY<MSG<TUR<GIT1071- Freeze Star -
Creation Energizer + Frostbite Stopwatch<WAI9999<END
```
Start.tsc
```
#0620
<PRI<MSG<GIT1069Freeze Star
allows to place blocks
with a mouse.<NOD It
also makes Polar Star account
for momentum, <NOD chills
enemies, <NOD and creates
chilling ring around <NAM,<NOD
when they hold Polar Star or
Nemesis.<NOD<CLRCraft it?<YNJ0311<CLR<MM-<GIT0000.<WAI0020.<WAI0020.<WAI0020.<WAI0060<CLR<CMU0010<GIT1071<IT-0051<IT-0022<IT+0071<FL-0747<EQ-0256<FL-0741<E2-0021<DNA0193<MM-Created =Freeze Star=!<WAI0135<NOD<CLO<PS-0020<RMU<END
```

In Start.tsc event 0620 change `<GIT1069` to `<GIT1071`.

**Version**
1.44.1.1 and prior.

![image](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/77a36e61-0470-4179-beee-54728b75a9f8)
![image](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/69aaf65f-432c-4d36-96b0-e29e167bc3d5)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
