### ISSUE TITLE
Snake gets overpowered with miracle-crafted Flaming Booster

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#103]
The Snake gets auto-fire and splits into two projectiles normally with just the Propane Tank equipped, but when crafted using Propane Tank and Silver Locket to make Flaming Booster and if that is equipped, the Snake gets a much more rapid auto-fire which makes defeating enemies and even bosses far too easy.

1. In a run, happen to posses the Snake weapon, Propane Tank and Silver Locket (Use Snake with Propane Tank to get an idea).
2. Craft using a Miracle Matter at a terminal and combine Propane Tank and Silver Locket to make Flaming Booster.
3. Equip Flaming Booster and use the Snake weapon. See the difference.

Version 1.44.1.1 and prior.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
