### ISSUE TITLE
Miracle crafted Amphibian Medal orbiting NPC does not appear on next Depth or on load from save

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#106]
I believe there is no NPC with 'Appears when flag is set' and flag 872 on it that the game is placing on stage generation, going into boss rooms and loading from a save.

As going to the next depth or into a boss room while miracle crafted Amphibian Medal is currently equipped, the orbiting NPC will not show up.

**Version**
1.44.1.1 and prior.

My final thought; something is really wrong with the game's code that adds all the supporting NPCs with 'Appears when flag is set' and their attached flags when going to the next Depth, boss room or load from save. The issue #92 has a weird case, only for going into boss rooms or load from save, that sometimes it does not place the supporting NPC.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
