### ISSUE TITLE
Player dot in improved map system is not drawn in the right spot

### ISSUE THREAD

**Issue by Rapidgame7** [DoukutsuRandamu/IssueTracker#108]
**Describe the bug**
The player dot on the improved map doesn't seem to properly respect the player position, causing it to be drawn on the proper cell if the player is anywhere between the center and the right bound of a tile, or one cell to the left otherwise.

**Version**
1.44.1

**Video**
https://github.com/DoukutsuRandamu/IssueTracker/assets/14862618/94631363-cc1e-4d37-b756-ea3e85d5d3a6

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
