### ISSUE TITLE
Invidia bypasses boss protection

### ISSUE THREAD

**Issue by Rapidgame7** [DoukutsuRandamu/IssueTracker#110]
**Description**
While hugging the boss arena box from the left side, I shot a charged Invidia inside and provoked the boss, causing the arena box to be rebuilt and locking me out.

Originally, I thought it was because the boss protection boundaries were slightly off, so something like hugging a wall and hitting them would be the issue, but the next run confirmed that the actual issue is Invidia somehow bypassing boss protection: I charged a shot while being several tiles away from the boss arena and released it by accident towards a boss - they got provoked and locked me out.

**To Reproduce**
1. Charge an Invidia shot
3. Hit a boss

**Version**
1.44.1

**Screenshots**
![Randamu_2024-06-20_19-55-15](https://github.com/DoukutsuRandamu/IssueTracker/assets/14862618/f6b37ab4-29ea-414b-b7d1-2822b57cb65c)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.2.
