### ISSUE TITLE
Whimsical Star star collection does not trigger jingle

### ISSUE THREAD

**Issue by Rapidgame7** [DoukutsuRandamu/IssueTracker#111]
**Description**
The "all stars needed collected!" jingle does not start if the final star is collected by a Whimsical Star.

**To Reproduce**
1. Get a Whimsical Star
2. Use it to collect your 10th (or 20th) star
3. Listen

**Version**
1.44.1

**Video**
https://github.com/DoukutsuRandamu/IssueTracker/assets/14862618/936bb8e5-f6f7-4074-a954-7e2114311ef7

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
