### ISSUE TITLE
Floodtide cooldown weapon remains when Hellsweep is crafted

### ISSUE THREAD

**Issue by Rapidgame7** [DoukutsuRandamu/IssueTracker#114]
**Description**
When using the Floodtide attack special causing it to enter cooldown, then crafting Hellsweep while the cooldown is active, will force the cooldown effect to remain on screen.  
It's possible that this bug extends to getting rid of Floodtide by any means, like placing it in the inventory.

**To Reproduce**
1. Get Floodtide
2. Upgrade it to any level that has a special attack on swing
3. Craft Hellsweep or place weapon in inventory
4. Permanent cooldown icon on screen

**Version**
1.44.1

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
