### ISSUE TITLE
Window resolution is labeled 'controls' in the general options

### ISSUE THREAD

**Issue by zeroflafi** [DoukutsuRandamu/IssueTracker#116]
**Describe the bug**
as described in the title.

**To Reproduce**
Just go to the General Options in the title screen or pause menu.

**Version**
1.44.2.1

**Screenshots**
![image](https://github.com/user-attachments/assets/c6be31ae-6908-45bb-becb-f536bf43844a)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.2.
