### ISSUE TITLE
NPCs that appear when items are equipped spawn even when the player is invisible

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#12]
The only place this is really obvious is in the ending cutscene, since the player's position is different than that of the NPC that represents the player.

...At least, I'm assuming that is an NPC and not the player. If that is the actual player, it would be a really strange bug.

![](https://cdn.discordapp.com/attachments/927187005308289038/1121127300797313155/Screen_Shot_2023-06-21_at_12.19.32_PM.png)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 (by making allies follow Quote NPCs when player is invisible from scripting)
