### ISSUE TITLE
Some dialogue boxes have gaps between text lines

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#13]
It seems that dialogue lines that have 26-28 characters cause the text to create a blank line in between it and the next line. Several text boxes in Randamu have awkward gaps in between lines.

This will be updated with more locations once I find more.
![](https://cdn.discordapp.com/attachments/927187005308289038/1121126376796332052/Screen_Shot_2023-06-21_at_12.15.10_PM.png)
![Screen Shot 2023-06-21 at 12 16 35 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/adde47e0-d2aa-430d-8e7f-ef3c478c1759)
![Screen Shot 2023-06-21 at 12 20 36 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/58d391ad-a45c-4722-844e-cee538b1c158)
^ (not pictured, the <NOD rectangle here is printed on the next line)
![Screen Shot 2023-06-21 at 6 36 13 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/1e700047-7589-410c-9b7f-0f35c280faa6)
![Screen Shot 2023-06-21 at 6 42 39 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/efac69a2-fa2d-4319-9188-c175324373fa)
![Screen Shot 2023-06-25 at 1 11 05 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/971f3989-0f39-4f66-86ed-27741c6268cf)
![Screen Shot 2023-07-08 at 2 43 21 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/9cc43926-ef83-4842-aff4-53cd055614ae)

**Comment by TrashboxBobylev** [comment]
Fixed cases shown here in 1.43 beta-4
