### ISSUE TITLE
Opening the pause menu in the credits results in a level appearing in the background

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#14]
![Screen Shot 2023-06-21 at 6 26 17 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/6008d2d8-265f-4e60-a0bd-3270682bb61e)

It disappears again once you exit the menu.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 (by not allowing to open pause menus during credits sequence).
