### ISSUE TITLE
The star and "Depth" counter numbers appear in the credits

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#15]
![Screen Shot 2023-06-21 at 12 21 21 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/0d5b7035-c613-43d8-9ecf-79d6e75231a1)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 (alongside with score counter and cooldown display)
