### ISSUE TITLE
All NPCs in the boss arena have invincibility until it is entered

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#18]
![Screen Shot 2023-06-25 at 3 15 38 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/8b323c87-1bdc-4dc1-94f1-8256eaff9e39)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 beta-2.
