### ISSUE TITLE
Water surface tiles don't override surface tiles beneath them when they spread

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#19]
I get the feeling this has probably been known about for a long time. Still, I think it's about time to finally fix this, as it looks kind of ugly.

![Screen Shot 2023-06-25 at 3 22 46 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/cb927458-a79e-487b-b7ed-52e25627e5ee)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 beta-2, by adding more checks to turn water surfaces into just water.
