### ISSUE TITLE
The boss arena range is slightly too short

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#20]
I'm able to get to about approximately this position before the boss is able to be hurt. This issue only exists on the left side, the right side does seem to extend all the way to the wall.

![Screen Shot 2023-06-25 at 3 31 46 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/cf0e7be3-0537-4330-b8e8-ae714db1d515)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 beta-2.
