### ISSUE TITLE
Objects on the same tile as semi-solid platforms don't show up on the map

### ISSUE THREAD

**Issue by bbaster** [DoukutsuRandamu/IssueTracker#21]
* Version 1.42.3.1 (beta 2)

Objects should have priority over semi-solids on the map.

This bug can potentially lead to players missing objects which is really annoying.

Here is an example:

![Screenshot_20230630_135053](https://github.com/DoukutsuRandamu/IssueTracker/assets/67292925/f23744d0-fa19-4fd5-a49f-275fa9b37f31)

Chest on the same tile as a semi-solid

![Screenshot_20230630_135057](https://github.com/DoukutsuRandamu/IssueTracker/assets/67292925/b02c1c85-5eed-4057-8efd-a9b5516cbfe7)

The chest not appearing on the map, with the semi-solid taking precedence

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 beta-3.
