### ISSUE TITLE
It's possible to reload the save file during the transition between the Doctor's phases

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#24]
Something similar might also be possible with Ballos' second phase since that is also triggered by an event, but i'd have to test that.

![Screen Shot 2023-07-08 at 2 53 43 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/758d3615-ce24-416e-89dc-8dc477364569)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44 (by making pause reloading only work on randomized stages).
