### ISSUE TITLE
The game doesn't load

### ISSUE THREAD

**Issue by musaticsgilbert** [DoukutsuRandamu/IssueTracker#3]
Unfortunately I can't add much else to the issue. The logs only show that the backend initialized.

```
[Wed Jun 14 20:20:49 2023] ------------------------------------
[Wed Jun 14 20:20:49 2023] Doukutsu Randamu v1.42.2.0 is starting.
[Wed Jun 14 20:20:49 2023] Backend is initialized in 4 ms.
```
Task manager doesn't show the process running.
Tested on Windows 11.

**Comment by musaticsgilbert** [comment]
I even naively overwrote the last working release with the new one so I had to load it back from my backup. Thank god there was one saved. I haven't updated for a while so the last working release that I tested is 1.34.0.0.

A minor suggestion regarding this: maybe put the version number at the end of the name of the release package, like doukutsu-randamu-win-stable-1-42-2-0.zip so it doesn't try to overwrite the last version.

**Comment by TrashboxBobylev** [comment]
Does it just close down or it shows any error messages?

**Comment by musaticsgilbert** [comment]
Unfortunately it just closes (I didn't even see the process pop up in task manager). I sent every log I got except if the program writes logs to other places too like AppData.

**Comment by musaticsgilbert** [comment]
Here is the folder after attempting to start the game.

![kép](https://github.com/DoukutsuRandamu/IssueTracker/assets/32367422/a526b5c2-7837-4e79-9c6a-5eebd8764de8)
