### ISSUE TITLE
Throwable blocks are not destroyed when Shadow Toroko is killed

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#32]
It seems that when a Shadow Toroko's blocks have not been thrown yet, and the Toroko is killed, the block will be left floating there. Eventually, it will latch onto other NPCs, such as the projectiles shot by Shadow Misery.

The easy solution would be to add a check in case 1 of Toroko's blocks' code to see if npc->pNpc->code_char != 140, and if that is the case destroy the block entity. Like so:

	if (npc->pNpc->code_char != 140)
		npc->cond |= 8;
![Screen Shot 2023-07-10 at 12 15 03 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/47bdb03b-66fa-40be-aa39-5bc159d73100)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43 beta-4
