### ISSUE TITLE
The buffed Level 3 Boomerang Blade deals way too much damage at times

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#38]
It deals seemingly random amounts of damage, sometimes only around 18, occasionally around 70 damage. The weapon does the absurd amount of damage more consistently both on enemies up close, and enemies with big hitboxes like the Power Critter.
![Screen Shot 2023-09-11 at 7 12 00 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/f5f7ddd7-afca-4cfa-99ba-e2c6be6e1ada)

**Comment by TrashboxBobylev** [comment]
Does this happen in 1.43's beta?

**Comment by DrippingYellow** [comment]
Sorry, i should've mentioned this was in the 1.43 beta! I assumed you would have gotten that from the fact i specified "Buffed boomerang blade", but i guess it could've been buffed at some other time. I'm not sure if this also happens in 1.42.3, though...

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43 RC-1
