### ISSUE TITLE
Flames from various weapons zip to the right when near/inside of a ceiling

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#4]
Self-explanatory. Easiest way to recreate this is by using the Lv. 2 Boomerang Blade in a one-tile high gap.
![Screen Shot 2023-06-16 at 2 38 59 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/5a485daa-d913-40c3-8cf6-7a71ff1f88ce)

**Comment by TrashboxBobylev** [comment]
This is actually a "feature" from regular Cave Story - certain bullets will always try to go out of blocks when colliding with them.
