### ISSUE TITLE
Terra Boots refer to Nice Skates as "Nice Shoes" in crafting description

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#42]
![Screen Shot 2023-09-13 at 8 13 57 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/107ef426-7e81-4716-a6a1-0de4a3bbdf02)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43 beta-4
