### ISSUE TITLE
Entering the next floor with Hunter adds Lily's items and weapons

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#43]
[Load this profile, and enter the door just to the right of you.](https://github.com/DoukutsuRandamu/IssueTracker/files/12614455/Profile.json.zip)
![Screen Shot 2023-09-14 at 7 20 08 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/16ff1161-39e2-491e-92c8-372f47709828)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43 beta-4
