### ISSUE TITLE
Level 1 Bubbler projectile interacts with grass and makes it wet, to hilarious results

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#44]
The same might be true of the fire in the Endless Frontdoors, i'll have to test that if i find a floor with that theme.
![Screen Shot 2023-09-14 at 7 54 34 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/7cc66880-af8e-4adb-9c16-1eda4aea1551)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43 beta-4
