### ISSUE TITLE
Grassy Bushtown on 2nd Campaign

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#46]
Loading "Grassy Bushtown" tileset (stage) on 2nd Campaign (from Depth 11), either randomly or forced with config.json ("tileset":"Grassy Bushtown") will **freeze** the game. Versions 1.43.0.5 and prior.

My first bug report here.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.34.1.
