### ISSUE TITLE
The game randomly freezes on Sky Islands

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#47]
The game has a tendency to freeze on "Sky Islands" tileset on a certain depth? I had it with Random Size for maps turned on. Versions 1.43.0.5 and prior.

**Comment by TrashboxBobylev** [comment]
`randomSizeMode` config is unstable in general, so this is kind of applies to many maps in general.

**Comment by Fluff8836** [comment]
If need be, I'll provide profile.json & config.json.

I'm going to do a run with Sky Islands being locked in config.json, save the game at some point. Provide the files when the freeze happens.

**Comment by Fluff8836** [comment]
I finally figured it out what froze the game on Sky Islands. It's the equipped Nano Quiver item and with the Gimmick Doggy. I will provide the config.json and profile.json for your testing. Here are the steps:

1. Load the save. As soon as you load it, you may equip the Nano Quiver via the Inventory. (You'll take damage because of the puppy next to the save)
2. Go towards the lower-right of the stage. You'll find a group of puppies there. Mine away blocks to the right to create a tunnel for puppies to run out of bounds to the right.
3. Once you see the puppies disappear to the right, if you have Nano Quiver equipped, the game will **freeze**. The game will not unless you equip the Nano Quiver.

Here are the files:
[config.json](https://github.com/DoukutsuRandamu/IssueTracker/files/13694297/config.json)
[Profile.json](https://github.com/DoukutsuRandamu/IssueTracker/files/13694298/Profile.json)

**Comment by TrashboxBobylev** [comment]
Fixed the puppy issue at least in 1.43.1.
