### ISSUE TITLE
Super Booster's damaging trails

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#48]
Super Booster's "trail" npcs that damages enemies when equipped also applies to "trail" npcs generated by projectiles, example is Missiles from Turrets and they are damaging themselves, and also applies to the "trail" generated from Speed Shoes and the crafted Ominiquick Sneakers when equipped. I caught this on version 1.42.3 before, and I think this is not fixed. Yet to replicate this on the latest version 1.43.0.5.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43.1.
