### ISSUE TITLE
Sheep can jump in the air

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#5]
It seems like sheep do not have any checks for whether they are on the ground or not, as they randomly jump even while they are airborne, sometimes while they are already jumping.

Shown: A pit full of sheep, with one having jumped higher than normal as a result of this glitch
![Screen Shot 2023-06-16 at 3 15 56 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/d7426f7a-c3b3-43fe-bec5-4d45bc993f60)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3.
