### ISSUE TITLE
Item deequipping with NPCs on PC issues

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#50]
**Rewritten as of 12/16/2023**
Deequipping items are causing problems with flags and npcs such as orbiting medals, Little Man and Curly Brace, reenabling their flags when their entities are deleted. To replicate the equip bug in-game before fixing them as instructed below, have affected items equipped and go to the door to the next Depth. Then deequip the item, the equipped mark does not disappear or reappears once unless you deequip it again.

To fix, please move all <DNAs to **before** all <FL-s in ArmsItem. Do the same in Stages/Start when player crafts new items. Items affected below:

   - Badge of Love (Crafted Curly's Underwear + Iron Bond. Also does not deequip the Iron Bond's health regeneration. Please add <EQ-0064.)
   - Amphibian Medal (Crafted Alien Medal + Battery Pack. This also happens to be <DNP which only deletes NPCs of ID. Please change <DNP to <DNA.)
   - Clay Figure Medal
   - Curly's Underwear
   - Alien Medal
   - Little Man's Underwear (Crafted Curly's Underwear + Little Man.)

Version 1.43.0.5 and prior.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43.1.
