### ISSUE TITLE
Message display issues for version 1.43.0.5

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#51]
This is a list of issues of message displays I have encountered for this version. 1.43.0.5

- Rocket Launcher's description message still mentions Quote, even when you are playing as a different character. Change "Quote" to "player" or "user" and the pronoun "him" to "them" please. ArmsItem event #1005.
- Energy Crystal's description message advances too quickly. Please add <KEY before <MSG, change <WAI0040 to <NOD, and add <FRE before <WAI9999. ArmsItem event #6014.
- There is a typo on the message when equipping Water Thrusters. Displays "Equipped Water Thursters." Thrusters is misspelled. ArmsItem event #6042.

I may add more to the list unless this is closed.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43.1.
