### ISSUE TITLE
Defeating the final boss will record player as drowned/never seen again in Rankings.

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#52]
- Defeating the final boss on Depth 20 will record as player drowned/never seen again on the Rankings. The <SCR may have been used before several map transitioning in the ending cutscene and credits. Please remove <SCR in Ballo1, event #1001, and then place <SCR in 0, event #0100. This will record as player walking with no death entity beside it and properly record as a completed game among games played. Version 1.43.0.5 and prior.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.34.1.
