### ISSUE TITLE
Depth 20 won't be Final Chamber if playing with locked tileset set in config.json

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#53]
Depth 20 (or 12 with FastRun enabled) will not be the Final Chamber if the tileset is locked onto something else than Shadowbuilt Crags in config.json for Depth 19 (or 11 with FastRun enabled).
Suspected that Shadowbuilt Crags will always bring you to the Final Chamber when completed if that tileset is locked in config.json, no matter what Depth you are in. Version 1.43.0.5 and prior. Though I tested in a previous stable version, that being 1.42.3.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.34.1, with slight behavior change: tileset is no longer checked, but the "shadow depth" is, which is 19 on normal runs and 11 on fast runs.
