### ISSUE TITLE
Somehow the final boss on Depth 20 gets defeated on its second form without going to its third form.

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#54]
This has got to be Flag 1600 issue. On a version before 1.42.3, I played as Quote and was able to fight three forms of the final boss. Then on other characters, the boss got defeated on the second form. I don't know if that is the case, but it's got to be Flag 1600.

Replicated on 1.42.3 and I think it **may not have gotten fixed** in 1.43.0.5.

My suggestion is, on Ballo1 please add <FL-1600 before <END in event #0900, and move the <FL+1600 before <END in event #1000.

**Comment by TrashboxBobylev** [comment]
Did it work properly with your fix? I didn't change the script at all, it is just vanilla code.

**Comment by Fluff8836** [comment]
Yes. Was able to fight the third form with the fix.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.43.1.
