### ISSUE TITLE
Mimiga Village tileset on 2nd Campaign and Improved Map System mode

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#55]
The Improved Map System mode enabled and usage in Mimiga Village tileset (stage) in the 2nd Campaign (from Depth 11) is not very reliable when looking for treasure, because the **fires** all over the place are visible in the Improved Map System as **chest icons**. Version 1.43.0.5 and prior.

Screenshot shows Improved Map System with Start from Depth 11 enabled and tileset locked to Mimiga Village into config.json:
![firesaschestsimprovemap](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/3b285e5b-6c10-4c36-8880-b689261a2876)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.34.1.
