### ISSUE TITLE
Trying to scroll 10 entries in the Rankings when there's less than 10 entries crashes the game.

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#56]
Holding the Ability key and then pressing Next Weapon or Previous Weapon button on the Ranking screen to try to scroll the next or previous 10 entries when there are only less than 10 entries will **crash** the game. Any new entry to the Rankings and games played/completed count after game completion or death before closing the game normally will be lost if this action is performed. Versions 1.43.0.5 and prior.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.34.1.
