### ISSUE TITLE
Weird pause menu behaviors

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#57]
Going to the Tutorial, Rankings or returning to the Title Screen from the pause menu while having the inventory screen and/or map system open can yield unexpected results. Behaviors listed as follows:

Normal game screen:
- Tutorial: Runs the Tutorial event from Head. Normal.
- Rankings: Ends game and goes to Rankings. Normal.
- Return to Title: Ends game and goes to Title. Normal.

With inventory screen open:
- Tutorial: Tries to run the event from ArmsItem. Abnormal.
- Rankings: The music fades and nothing else happens. Abnormal.
- Return to Title: The game closes instead. Abnormal, but not a crash.

With Map System open:
- Tutorial: Will only run after closing the Map System. Normal.
- Rankings: The music fades and nothing else happens. Abnormal.
- Return to Title: The game closes instead. Abnormal, but not a crash.

With inventory screen open, _then_ selecting the Map System to open:
- Tutorial: Same behavior as when inventory screen is open, however it will **softlock** the game. Abnormal.
- Rankings: Same behavior as either things open. Abnormal.
- Return to Title: The game closes. However, with Turbo Text enabled, it takes you back to inventory with faded music and screen to black, won't see anything when inventory is closed. Abnormal, but not a crash.

Remember also, going to Tutorial with an event script running such as acquiring items or cutscenes will stop the previous script from following through, resulting in a lost item or not starting a boss fight. Versions 1.43.0.5 and prior.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.34.1.

- The tutorial now no longer can be activated if any text script is happening right now.
- Also fixed similar issues when Crafting menu is up.
