### ISSUE TITLE
Shadow Mimigas spawning appear like Toroko transforming before becoming darkened.

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#58]
Sometimes, when you enter Shadowbuilt Crags and there are Shadow Mimigas on the screen, they start out like Toroko, white in color and transform into Frenzied Toroko before they take on the Shadow coloration. I'll provide two sprite sheets, one original and one with my proposed fix. I recolored these the best I could. Version 1.43.0.5 and prior.
**Before:**
![NpcToro](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/134a596c-3af2-4616-b439-fab40e016d93)
**After:**
![NpcToro](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/11fb77a3-fb8f-4045-b472-d75805263456)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.34.1 (by removing transformation sequence entirely).
