### ISSUE TITLE
Interacting with the Terminal without Miracle Matter doesn't pause all game action

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#59]
Upon display of message box for no Miracle Matter, the game action is still going. This means any enemies close to the player that are chasing or attacking won't stop.

In start, event #0310, please add <PRI between <MMJ0311 and <MSG.

Version 1.43.0.5 and prior.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.34.1.
