### ISSUE TITLE
Noticeable glitches when time is slowed down

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#6]
These glitches all happen in Relativistic mode, and to a lesser extent in normal gameplay when using the Timeline Ring.

1. When a bullet is fired or an NPC is spawned while time is frozen, it is invisible at first. This is most apparent when the player shoots a bullet, or equips an item that spawns an NPC (e.g. Curly's Underwear, Little Man).
2. Semi-solid platforms do not react properly to the player's position. If time is frozen while on top of the platform, the player will be unable to drop through by pressing down, and if the player is below the platform when time is frozen, the player cannot stand on the platform.

The root cause of both of these glitches is that the object's code has not yet been run. For the first glitch, it happens because the object code has not yet set the sprite rect, while the second glitch happens because semi-solid platforms are NPCs, and thus cannot update their hitboxes based on the players actions while they are frozen.

A solution for the first glitch could be to give all NPCs a flag that allows them to be affected by time being slowed down, and set it at the end of the first frame. The second glitch could be fixed by making an exception in the time-slowing code for the semi-solid platform entity's ID.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 beta-2 by refactoring time stopping effect to allow for custom timestop effects for NPCs and bullets.
