### ISSUE TITLE
Infinite Life Capsule within 1st Campaign Boss Arenas

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#64]
If you shoot the Boss to start the fight with any Life Capsule that happen to be **_inside_** the arena, _then_ interacted with the Life Capsule, the Life Capsule will not disappear but still happen to _run the event and increase maximum life_ instead of "canceling" the event. This can be done as many times so long as the boss battle is active. Please check all 3 Life Capsule events in Start.tsc, +2HP, +3HP & +4HP.

Did it with character Curly Brace, making the Life Capsules deliver 4 HP instead of 3.
Version 1.43.1.0.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.
