### ISSUE TITLE
The trail NPC issues were fixed but...

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#67]
Follow-up on Issue #48 
The Super Booster trails **also don't do damage to enemies when boosting vertically.**

Partially broken feature but you can still damage enemies with the Super Booster trails when boosting _**horizontally.**_

Version 1.43.1.0

This comment has been edited. After further testing, found out the trails can damage enemies when player boosts horizontally. You make the call; fix the vertical boost trails, or modify the Super Booster's item description in ArmsItem and crafting description in Start.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.
