### ISSUE TITLE
Setting upgradeable weapons to items breaks miracle upgrade feature

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#68]
If you press [Ability] key on a upgradable weapon to set as an item at any point in the game, that weapon will **no longer have the miracle upgrade option on the Terminal for the rest of the game**, even if you select the weapon item to be placed back as a weapon. Affects Machine Gun, Snake & Floodtide.

Version 1.43.1.0

Original comment:

<s>"Upgrading Machine Gun to Gatling Gun with Snake on hand..."

If you use the Terminal and Miracle Matter to upgrade Machine Gun to Gatling Gun, while you have Snake that provides upgrade to Frontier Buster, the option to upgrade Snake to Frontier Buster on the Terminal **will be gone the whole game**, even when you have another Miracle Matter. Thus, the Snake that you have will remain the Snake after upgrading the Machine Gun.</s>

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.
