### ISSUE TITLE
The crash with crow teleportation on Reinforced+

### ISSUE THREAD

**Issue by TrashboxBobylev** [DoukutsuRandamu/IssueTracker#7]
Selfexplanatory. Another issue connected to rolling in the range of 0 with new RNG, that was not reported.

**Comment by DrippingYellow** [comment]
Wait... is this not the same as https://github.com/DoukutsuRandamu/IssueTracker/issues/2?

**Comment by TrashboxBobylev** [comment]
You know, this sounds like it. It was not obvious from screenshot or Discord discussions that #2 is about higher difficulty options.
