### ISSUE TITLE
Sara and Lily hurt sounds

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#70]
Somehow, the change from version 1.28 went undone. Sara and Lily characters is using the Quote hurt sound, no longer the Curly hurt sound. Fix them.

(Also, apply the Curly hurt sound on Misery, Ame and Serenity. It's very appropriate to apply that. The sound is feminine.)

Version 1.43.1.0.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.
