### ISSUE TITLE
Stages with Rocket Platforms and the Very Bottom of the Stage

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#77]
Before you go and release the new version, 'cause I keep forgetting to mention, something to consider about stages with randomly placed Rocket Platforms, ones you interact to launch upwards. 

The stages with Rocket Platforms in question are Egg Factory, Tech Facility, Chemical Lab & Subspace Warehouse.

Rocket Platforms are placed almost everywhere, but also at the very bottom of the stage.

If one does launch a Rocket Platform and happen to be directly below it as it falls back, one can get pushed into and be stuck there. They can get out using Nemesis or Invidia to break blocks. But, unfortunately if one is pushed into **the bottom of the stage,** they are **stuck there permanently and potentially ruining the run** unless they have and use an item such as the Chaos Key to teleport somewhere.

To Reproduce, that is getting stuck permanently, start a run with a locked tileset within config.json. Open config.json with Notepad and paste either of the following:
```
"tileset":"Egg Factory"
"tileset":"Tech Facility"
"tileset":"Chemical Lab"
"tileset":"Subspace Warehouse"
```
Rocket Platforms will be generated. Head to the very bottom of the stage and come across a Rocket Platform. Operate it and then get directly under the rocket, let it fall and you are stuck there permanently. **Border blocks cannot be destroyed by Nemesis or Invidia.**

Versions 1.43.1.0 and prior

![StuckByRocketatStageBottom](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/2ef382da-31c7-4186-aea8-0aca367a94b0)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44 (by making solid NPCs in general not push player beyond bottom of the stage).
