### ISSUE TITLE
Resource Overrides description text does not wrap

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#78]
After enabling a resource pack and starting Randamu, then selecting Resource Overrides from the menu, and finally the enabled resource pack, the description text clearly does not wrap in the text box and even goes off the screen. The screenshot below explains it all.

Versions 1.44.0.0 and prior.

![image](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/db65f2ff-d6c5-41ac-aea2-916eb8054d74)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.1.
