### ISSUE TITLE
Water Sprayer still shows as "Water Gun" on item pickup from a chest

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#79]
The item name in ArmsItem.tsc is correct, but something is amiss in Start.tsc:
```
#0238
<PRI<FLJ4001:0101<FL+4001<SOU0022<CNP0238:0021:0000
<MSGOpened the chest.<NOD<GIT0014<AM+0014:0100<CLR
<CMU0010Got the =Water Gun=!<WAI0150<NOD<GIT0000<CLO<RMU<END
```
Version 1.44.0.0

![image](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/eb17d7c6-643f-4358-a032-6c0c393b96b6)
![image](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/43e47253-c04a-4a29-90ec-847ad01cec0e)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.1.
