### ISSUE TITLE
Repeating patterns of ground tiles do not generate properly when "Random Size for Maps" is enabled.

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#8]
![Screen Shot 2023-06-19 at 6 33 44 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/a2503309-807d-461f-8b3a-67e45c6f2ef6)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3.
