### ISSUE TITLE
Fast Run mode does not end the game at Depth 12

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#81]
In a run with Fast Run mode enabled, in 2nd Campaign, it appears Depth 11 is not the "Shadow" stage, it's on Depth 12 and Teleporters will appear on even numbered stages instead of a Door. Because of this, the game will continue endlessly with Bosses on even numbered stages, with no Final Chamber in sight.

1. Go to 'Gameplay Options' and enable 'Finish in 6 Levels' then start a Run. (Enabling 2nd Campaign is optional)
2. Play your run up to Depth 11. It is not Shadowbuilt Crags... Enter Depth 12 and it is Shadowbuilt Crags with a Teleporter.
3. The run will continue endlessly, with a Boss Teleporter in even numbered stages. No Final Chamber in sight.

Version 1.44.0.0. Few prior versions may also be affected.

Make sure to set "Shadow" depth to 11 for Fast Run and somehow get flag 6999 enabled. Door should send to Final Chamber for Depth 12.

(I tried fixing using the easy way with TSC and paste a shadow flag jump (<FLJ6999:0126) in Event #0092 in Start.tsc. But turns out that did not do it.)

In the screenshot, note the Fast Run icon on the top-right of it.
![image](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/6fb6e573-0d06-41e9-b3c0-38c7f301f299)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.1.
