### ISSUE TITLE
Resonant difficulty Presses and the Top of the Stage

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#84]
One could hitch a ride on top of a Press when it retreats to it's resting spot in Resonant difficult and they could get stuck in the blocks. They can get out with Nemesis or Invidia. However, if blocks near the top border are taken out and if one rides the Press to the **Top of the Stage** (top border), they will be **stuck permanently and ruining the run** unless they have and use Chaos Key to teleport somewhere.

1. Start a Run in Resonant Difficulty and come across a Press. Be careful not to be too close when under.
2. Make it drop and break blocks around the top border
3. As the Press retreats, stand on top of it.
4. You'll squeeze through the top border and you cannot get free. **Border blocks cannot be destroyed by Nemesis or Invidia.**

Version 1.44.0.0.

![image](https://github.com/DoukutsuRandamu/IssueTracker/assets/153852440/bb187073-bcf5-4b47-8499-7592c696c6e4)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.1.
