### ISSUE TITLE
Miracle upgrade feature for weapons partially fixed, but...

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#86]
**Edited 5/23/2024 7:29 PM PDT**

Follow-up on issue #68. The Miracle upgrade feature gets retained when setting upgradable weapon to item, but gets broken when set back as a weapon (also plays sound if there's Miracle Matter). Won't be able to use Miracle Matter on upgradeable weapon **unless it is set back to an item again.**

1. Set Machine Gun, Floodtide or Snake to item using [Ability] key. (You hear a sound if there's Miracle Matter.)
2. Set the weapon item back to weapon by selecting it. (You hear a sound if there's Miracle Matter.)
3. Interact with Terminal (with Miracle Matter). The weapon upgrade option is gone.
4. Repeat step 1, and then 3. The weapon upgrade option returns.

Version 1.44.0.0.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.1.

**Comment by Fluff8836** [comment]
Um, that did not further fix this bug. Setting upgradable weapon item back as weapon still removed the miracle upgrade option, **got to still set it back as an item if it was set as an item before.**

Version 1.44.1.1.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
