### ISSUE TITLE
Crafting with full inventory discards crafted item

### ISSUE THREAD

**Issue by Rapidgame7** [DoukutsuRandamu/IssueTracker#89]
**Describe the bug**
While playing as Sue with an inventory with 38 items (the maximum that doesn't break the inventory display is 35), I tried crafting a Military Armament.  
Both required items were consumed, but the result item was not placed in the inventory.

**To Reproduce**
1. Have a full inventory with three extra items (you can quickly get there by turning weapons into items)
2. Try crafting

**Version**
1.44

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.1.
