### ISSUE TITLE
Semi-solid platforms have priority on the map over solid tiles

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#9]
When semi-solid platforms spawn inside of walls, on that tile on the map the game will display the platform's icon, instead of the tiles.

![Screen Shot 2023-06-20 at 6 16 44 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/3f42c31c-b536-4860-bee9-b6901c66f0f8)
![Screen Shot 2023-06-20 at 6 17 00 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/6cc049b3-58c8-49e2-bbb2-deec2f70d8ed)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.42.3 beta-2 by removing platforms inside walls altogether.
