### ISSUE TITLE
Bug from #64 not fixed. Infinite Life Capsule within 1st Campaign Boss Arenas

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#91]
Follow-up on issue #64. Unfortunately, when I ran into the boss arena with a Life Capsule inside and started a boss fight, and interact with the Life Capsule, **the bug still persists.** Still runs the Life Capsule pickup event instead of canceling out. (There's still the *ting* sound and the capsule doesn't disappear)

1. When you get the chance, in Depths 4 and 8 (2 and 4 in Fast Run), check the Map System and look for the Boss Arena with any Life Capsule inside them. (If there's a Life Capsule directly above the Boss Arena, you may break blocks to make it _fall_ into the Boss Arena)
2. Break and enter the arena, then shoot the boss to make it active.
3. Interact with the Life Capsule inside the arena. Still runs a Life Capsule pickup event with fanfare. Life Capsule makes *ting* sound and does not disappear during active boss.
4. Repeat step 3 as many times.

Version 1.44.0.0.

**Comment by TrashboxBobylev** [comment]
Addressed with commits that fix #85, so... fixed in 1.44.1.
