### ISSUE TITLE
Curly Brace ally doesn't appear when entering Depth 10, 2nd Campaign boss chambers and ending cutscenes

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#92]
I really hope you also got this addressed too...
**This is a weird and rare issue, could be some item conflict going on. Has anyone else ran into the same issue on their runs?**
When entering Depth 10, 2nd Campaign boss chambers and ending cutscenes while having Curly's Underwear / Badge of Love / Little Man's Underwear equipped, **Curly Brace ally will _sometimes_ not appear on the player. (Unless in a boss chamber they de-equip and re-equip the item)** This issue _may also apply_ to Little Man item and Little Man not appear as well...

1. Have Curly's Underwear / Badge of Love / Little Man's Underwear and equip it.
2. Enter Depth 10 (6 in Fast Run, The King's Table), 2nd Campaign boss chamber or Final Chamber / beat final boss and enter an ending cutscene.
3. Curly ally _sometimes_ does not appear. In Depth 10 or 2nd Campaign boss chamber, can de-equip and re-equip to summon Curly again.

Version 1.44.0.0

**To assist with this rare issue, here are the files:**
[config.json](https://github.com/DoukutsuRandamu/IssueTracker/files/15482697/config.json)
[Profile.json](https://github.com/DoukutsuRandamu/IssueTracker/files/15482698/Profile.json)
[seed.txt](https://github.com/DoukutsuRandamu/IssueTracker/files/15482699/seed.txt)

This was done with seed ASCII "PressTrap" resulting in 3920413154 (Enter ONLY PressTrap in seed.txt, CANNOT accept 10-digit number--limited to 9-digits--a bug reported not planned to be fixed will result as 0392041315 instead). I did a run with gimmick locked to "Treasure" in order to collect the stuff needed to replicate the issue. **Must not load** from a save until Depth 9.

The Profile data has Badge of Love equipped and currently on Depth 9, **however,** upon loading the save, the Curly ally does not show up. Will only show up after de-equipping and re-equipping Badge of Love. The ally will not show up at the King's Table. She does happen to reappear on normal depths while Badge of Love still equipped.

**Comment by TrashboxBobylev** [comment]
...did this happen before 1.44?

**Comment by Fluff8836** [comment]
Nothing happened on earlier versions. Was fine on my earlier runs.

No problems on 1.43.1 and earlier.

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.1.

**Comment by Fluff8836** [comment]
Understood that there was flag issues going on.

I did a Fast Run to verify the bugs I had come across have fixed. Unfortunately, this bug for the Curly Brace ally did not get fixed. I will attach a Profile.json here.

This save is a Fast Run mode at Depth 11, correctly at Shadowbuilt Crags. Has Curly's Underwear equipped, but the Curly Ally will not show up on load.

[config.json](https://github.com/user-attachments/files/15518978/config.json)
[Profile.json](https://github.com/user-attachments/files/15518979/Profile.json)

Version 1.44.1.1.

**Comment by TrashboxBobylev** [comment]
I hate my own life...

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
