### ISSUE TITLE
It's possible to drop mini-bosses out of their arena

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#95]
This is an edge case to the whole "attacking bosses outside of the arena" situation that I didn't think about until now. I tested it on this Balrog fight by destroying the blocks beneath him, and lo and behold, it's possible to take the boss outside of their arena. This can result in either an incredibly difficult fight that takes place on the random terrain with no block placing/destroying abilities, or an outright softlock if you damage the boss from inside the arena, as the holes are filled in and you become trapped.

I encountered this bug while playing 1.44.0 (it wasn't until i checked the itch.io page to get to the GitHub page that I found out that 1.44.1 had been released two minutes prior), but since I didn't see any fixes relating to the miniboss arena, it most likely applies to the next version as well.

![Screen Shot 2024-05-30 at 12 11 00 PM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/96eeb40a-82b1-4646-903f-2ce0828de696)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
