### ISSUE TITLE
Zombie Dragons float when knocked back

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#97]
Self-explanatory, I think. Hitting them with the Lead Weight or Floodtide or another weapon that gives knockback will cause them to float, likely due to not being programmed with gravity in the original game. This also means that they will float even as blocks beneath them are destroyed.

![Screen Shot 2024-05-31 at 11 07 01 AM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/08271582-a947-49af-b249-4217f0465e29)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
