### ISSUE TITLE
2nd Campaign Clouds and Blizzards spawning placement issues depending on window resolution

### ISSUE THREAD

**Issue by Fluff8836** [DoukutsuRandamu/IssueTracker#98]
In the 2nd Campaign where some hazards are spawning, like clouds on Windy Islands and Dreamscape Hubworld (Sky Islands and Dreamful Beachscape on versions prior to 1.44) and blizzards on Tsurara Grotto (Hekichu Caverns on versions prior to 1.44), they spawn correctly from the right side of the screen on default resolution Windowed 852x480.

However, when playing with shorter resolutions on these tilesets at the 2nd Campaign, **the hazards all spawn too far to the right** and take a while moving left until they show up on screen. And when playing with higher resolutions, they like **pop up suddenly at near the right of the screen.** Lastly, when playing on Fullscreen (my monitor's maximum resolution is 1920x1080), the hazards **pop up at near the MIDDLE of the screen**, which can be an annoyance, especially where freezing blizzards that can pop up on the player and chilling them for a long long time!

1. Lock either of the tilesets in config.json. Open config.json in Notepad and paste either of the following:
```
"tileset":"Windy Islands",
"tileset":"Dreamscape Hubworld",
"tileset":"Tsurara Grotto",
"tileset":"Sky Islands",
"tileset":"Dreamful Beachscape",
"tileset":"Hekichu Caverns",
```
Also paste/change `"secondCampaign": true,` too.
2. In General Options, select Controls (?) to Windowed 852x480. Close and reopen Randamu.
3. Start a run and look at the hazards coming from the right side of the game screen.
4. Quit and return to the main menu, repeat step 2 but set to the **lowest** resolution. Again, close and reopen Randamu.
5. Start a run and the **hazards can take a little while** to show.
6. Quit and return to the main menu, repeat step 2 but set to the **highest** resolution. Again, close and reopen Randamu.
7. Start a run and the **hazards can pop up mid-right** of the game screen.
8. Quit and return to the main menu, repeat step 2 but now set to **Fullscreen.** Again, close and reopen Randamu.
9. Start a run and, depending on monitor resolution, **the hazards pop up near the middle** of the game screen. (Based on 1920x1080)

**Version**
1.44.1.1 and prior. I'd say ALL versions...

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2.
