### ISSUE TITLE
Legacy Graphics lacks sprites for the Floodtide/Hellsweep cooldown and powerup status effects

### ISSUE THREAD

**Issue by DrippingYellow** [DoukutsuRandamu/IssueTracker#99]
In ArmsImage.png:
![Screen Shot 2024-06-04 at 11 03 16 AM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/753e20be-70a5-4ec8-bcc0-b6d047532ee4)

In ArmsImageLegacy.png:
![Screen Shot 2024-06-04 at 11 04 05 AM](https://github.com/DoukutsuRandamu/IssueTracker/assets/106562603/fcff907b-4039-410d-a6b0-e51466d2b8f6)

**Comment by TrashboxBobylev** [comment]
Fixed in 1.44.2 (by moving cooldown icons into their own file).
